use anyhow::Result;
use std::path::PathBuf;

use crate::models::software::{
    ArchiveFormat, ArchiveInfo, CatalogEntry, CatalogVersion, ConfigField, ConfigFieldType,
    ConfigSchema, HealthCheckSpec, LogSource, LogSourceKind, MirrorSource, SoftwareCategory,
};

use super::{
    ConfigContext, DataDirContext, HealthContext, InstallContext, LogContext, SoftwareProvider,
    StartCommand, StartContext, default_log_sources, resolve_data_dir,
};

#[cfg(windows)]
const CREATE_NO_WINDOW: u32 = 0x08000000;
#[cfg(not(windows))]
const CREATE_NO_WINDOW: u32 = 0;

fn config_str(c: &serde_json::Value, key: &str, default: &str) -> String {
    c.get(key)
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| default.to_string())
}

fn config_u64(c: &serde_json::Value, key: &str, default: u64) -> u64 {
    c.get(key).and_then(|v| v.as_u64()).unwrap_or(default)
}

pub struct ElasticsearchProvider;

impl ElasticsearchProvider {
    pub fn new() -> Self {
        Self
    }
}

impl Default for ElasticsearchProvider {
    fn default() -> Self {
        Self::new()
    }
}

impl SoftwareProvider for ElasticsearchProvider {
    fn key(&self) -> &str {
        "elasticsearch"
    }

    fn catalog_entry(&self) -> CatalogEntry {
        let version = "8.19.0".to_string();
        // 平台差异在编译期选取对应官方包（Windows 为 zip，其余为 tar.gz）。
        #[cfg(windows)]
        let (url, format) = (
            "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.19.0-windows-x86_64.zip".to_string(),
            ArchiveFormat::Zip,
        );
        #[cfg(target_os = "linux")]
        let (url, format) = (
            "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.19.0-linux-x86_64.tar.gz".to_string(),
            ArchiveFormat::TarGz,
        );
        #[cfg(target_os = "macos")]
        let (url, format) = (
            "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.19.0-darwin-x86_64.tar.gz".to_string(),
            ArchiveFormat::TarGz,
        );
        #[cfg(not(any(windows, target_os = "linux", target_os = "macos")))]
        let (url, format) = (
            "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.19.0-linux-x86_64.tar.gz".to_string(),
            ArchiveFormat::TarGz,
        );

        let versions = vec![CatalogVersion {
            version: version.clone(),
            mirrors: vec![MirrorSource {
                name: "i18n:elasticsearchOfficial".to_string(),
                url,
                builtin: None,
            }],
            archive: ArchiveInfo {
                format,
                size: None,
                sha256: None,
            },
        }];

        CatalogEntry {
            key: "elasticsearch".to_string(),
            name: "Elasticsearch".to_string(),
            description: "分布式搜索与分析引擎".to_string(),
            description_i18n: Some("catalogDesc.elasticsearch".to_string()),
            category: SoftwareCategory::Search,
            icon: "mdi:magnify".to_string(),
            versions,
            default_version: version,
        }
    }

    fn post_install(&self, ctx: &InstallContext) -> Result<()> {
        // 预创建默认数据目录并写入默认 elasticsearch.yml（启动时会按 config 覆写）。
        let config_dir = ctx.install_dir().join("config");
        std::fs::create_dir_all(&config_dir)?;
        let data_path = ctx.install_dir().join("data");
        std::fs::create_dir_all(&data_path)?;
        let yml = format!(
            "# Generated by opx - Elasticsearch (default)\n\
             network.host: 127.0.0.1\n\
             http.port: 9200\n\
             transport.port: 9300\n\
             discovery.type: single-node\n\
             xpack.security.enabled: false\n\
             path.data: {data_path}\n",
            data_path = data_path.to_string_lossy(),
        );
        std::fs::write(config_dir.join("elasticsearch.yml"), yml)?;
        Ok(())
    }

    fn start_command(&self, ctx: &StartContext) -> Result<StartCommand> {
        // ES 8.x 需要 JDK 17+：复用用户已配 JDK（ES_JAVA_HOME）。
        let jdk = ctx
            .jdk_install_path
            .as_deref()
            .ok_or_else(|| anyhow::anyhow!("请先安装 JDK/JRE 并在配置中选择后再启动"))?;

        let port = config_u64(&ctx.config, "port", 9200);
        let transport_port = config_u64(&ctx.config, "transport_port", 9300);
        let heap = config_str(&ctx.config, "heap", "1g");
        let network_host = config_str(&ctx.config, "network_host", "127.0.0.1");
        let data_path =
            resolve_data_dir(&ctx.config, "data_path", "data", &ctx.install_path);

        // 按 config 生成 config/elasticsearch.yml（覆盖 post_install 的默认值）。
        // .yml 不被 config_editor 支持，故由 Provider 自行生成。
        let config_dir = PathBuf::from(&ctx.install_path).join("config");
        std::fs::create_dir_all(&config_dir)?;
        let yml = format!(
            "# Generated by opx - Elasticsearch\n\
             network.host: {network_host}\n\
             http.port: {port}\n\
             transport.port: {transport_port}\n\
             discovery.type: single-node\n\
             xpack.security.enabled: false\n\
             path.data: {data_path}\n",
            network_host = network_host,
            port = port,
            transport_port = transport_port,
            data_path = data_path.to_string_lossy(),
        );
        std::fs::write(config_dir.join("elasticsearch.yml"), yml)?;

        let bin = if cfg!(windows) {
            "bin/elasticsearch.bat"
        } else {
            "bin/elasticsearch"
        };

        let mut env_vars = std::collections::BTreeMap::new();
        env_vars.insert("ES_JAVA_HOME".to_string(), jdk.to_string());
        env_vars.insert(
            "ES_JAVA_OPTS".to_string(),
            format!("-Xms{heap} -Xmx{heap}"),
        );

        Ok(StartCommand {
            program: bin.to_string(),
            args: vec![],
            env_vars,
            working_dir: PathBuf::from(&ctx.install_path),
            creation_flags: CREATE_NO_WINDOW,
            first_run_init: None,
        })
    }

    fn health_check(&self, ctx: &HealthContext) -> HealthCheckSpec {
        let port = ctx
            .config
            .get("port")
            .and_then(|v| v.as_u64())
            .map(|p| p as u16)
            .unwrap_or(if ctx.port > 0 { ctx.port } else { 9200 });
        HealthCheckSpec::Tcp {
            port,
            timeout_ms: 1000,
        }
    }

    fn config_schema(&self) -> Option<ConfigSchema> {
        Some(ConfigSchema {
            fields: vec![
                ConfigField {
                    key: "port".to_string(),
                    label_i18n: "configField.esPort".to_string(),
                    field_type: ConfigFieldType::Port,
                    default_value: serde_json::json!(9200),
                    section: None,
                    description_i18n: Some("configField.esPortDesc".to_string()),
                },
                ConfigField {
                    key: "transport_port".to_string(),
                    label_i18n: "configField.esTransportPort".to_string(),
                    field_type: ConfigFieldType::Port,
                    default_value: serde_json::json!(9300),
                    section: None,
                    description_i18n: Some("configField.esTransportPortDesc".to_string()),
                },
                ConfigField {
                    key: "heap".to_string(),
                    label_i18n: "configField.esHeap".to_string(),
                    field_type: ConfigFieldType::Size {
                        units: vec!["m".to_string(), "g".to_string()],
                    },
                    default_value: serde_json::json!("1g"),
                    section: None,
                    description_i18n: Some("configField.esHeapDesc".to_string()),
                },
                ConfigField {
                    key: "network_host".to_string(),
                    label_i18n: "configField.esNetworkHost".to_string(),
                    field_type: ConfigFieldType::Text,
                    default_value: serde_json::json!("127.0.0.1"),
                    section: None,
                    description_i18n: Some("configField.esNetworkHostDesc".to_string()),
                },
                ConfigField {
                    key: "data_path".to_string(),
                    label_i18n: "configField.esDataPath".to_string(),
                    field_type: ConfigFieldType::Text,
                    default_value: serde_json::json!("data"),
                    section: None,
                    description_i18n: Some("configField.esDataPathDesc".to_string()),
                },
                ConfigField {
                    key: "jdk".to_string(),
                    label_i18n: "configField.esJdk".to_string(),
                    // options/labels 由 get_config_schema 命令层动态填充（已装 JDK/JRE）
                    field_type: ConfigFieldType::Select {
                        options: vec![],
                        labels: vec![],
                    },
                    default_value: serde_json::json!(""),
                    section: None,
                    description_i18n: Some("configField.esJdkDesc".to_string()),
                },
            ],
            ephemeral_keys: vec![],
        })
    }

    fn log_sources(&self, ctx: &LogContext) -> Vec<LogSource> {
        let mut sources = default_log_sources(ctx);
        let file = PathBuf::from(&ctx.install_path)
            .join("logs")
            .join("elasticsearch.log");
        sources.push(LogSource {
            path: file.to_string_lossy().to_string(),
            kind: LogSourceKind::ProviderFile,
            has_levels: true,
            level_pattern: None,
        });
        sources
    }

    fn data_dirs(&self, ctx: &DataDirContext) -> Vec<PathBuf> {
        vec![resolve_data_dir(
            &ctx.config,
            "data_path",
            "data",
            &ctx.install_path,
        )]
    }

    fn min_jdk_version(&self) -> Option<u32> {
        // Elasticsearch 8.x 需要 JDK 17+
        Some(17)
    }

    fn config_file_path(&self, _ctx: &ConfigContext) -> Option<PathBuf> {
        // .yml 不被 config_editor 支持，配置由 start_command 自行生成
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> serde_json::Value {
        serde_json::json!({
            "port": 9200,
            "transport_port": 9300,
            "heap": "1g",
            "network_host": "127.0.0.1",
            "data_path": "data",
            "jdk": "",
        })
    }

    fn test_install_path() -> String {
        let p = std::env::temp_dir().join("opx_test_elasticsearch");
        let _ = std::fs::create_dir_all(&p);
        p.to_string_lossy().to_string()
    }

    #[test]
    fn key_and_category() {
        let p = ElasticsearchProvider::new();
        assert_eq!(p.key(), "elasticsearch");
        assert_eq!(p.catalog_entry().category, SoftwareCategory::Search);
    }

    #[test]
    fn config_file_path_is_none() {
        let p = ElasticsearchProvider::new();
        let ctx = ConfigContext {
            install_path: test_install_path(),
            version: "8.19.0".to_string(),
            config: test_config(),
        };
        assert!(p.config_file_path(&ctx).is_none());
    }

    #[test]
    fn min_jdk_version_is_17() {
        assert_eq!(ElasticsearchProvider::new().min_jdk_version(), Some(17));
    }

    #[test]
    fn start_command_generates_elasticsearch_yml() {
        let p = ElasticsearchProvider::new();
        let install_path = test_install_path();
        let ctx = StartContext {
            installed_id: "es-1".to_string(),
            install_path: install_path.clone(),
            version: "8.19.0".to_string(),
            config: test_config(),
            custom_start_command: None,
            init_password: None,
            jdk_install_path: Some("C:\\jdk-17".to_string()),
            mysql_install_path: None,
        };
        let cmd = p.start_command(&ctx).expect("start_command ok");
        #[cfg(windows)]
        assert_eq!(cmd.program, "bin/elasticsearch.bat");
        #[cfg(not(windows))]
        assert_eq!(cmd.program, "bin/elasticsearch");
        assert!(cmd.args.is_empty());
        assert_eq!(cmd.env_vars.get("ES_JAVA_HOME"), Some(&"C:\\jdk-17".to_string()));
        assert!(cmd.env_vars.get("ES_JAVA_OPTS").map(|s| s.contains("-Xmx1g")).unwrap_or(false));

        let yml = std::fs::read_to_string(
            PathBuf::from(&install_path)
                .join("config")
                .join("elasticsearch.yml"),
        )
        .expect("elasticsearch.yml written");
        assert!(yml.contains("discovery.type: single-node"));
        assert!(yml.contains("xpack.security.enabled: false"));
        assert!(yml.contains("http.port: 9200"));
        assert!(yml.contains("transport.port: 9300"));
    }

    #[test]
    fn health_check_is_tcp_9200() {
        let p = ElasticsearchProvider::new();
        let hc = p.health_check(&HealthContext {
            installed_id: "es-1".to_string(),
            install_path: test_install_path(),
            port: 0,
            config: test_config(),
        });
        match hc {
            HealthCheckSpec::Tcp { port, timeout_ms } => {
                assert_eq!(port, 9200);
                assert_eq!(timeout_ms, 1000);
            }
            _ => panic!("expected Tcp health check"),
        }
    }

    #[test]
    fn start_command_errors_without_jdk() {
        let p = ElasticsearchProvider::new();
        let ctx = StartContext {
            installed_id: "es-1".to_string(),
            install_path: test_install_path(),
            version: "8.19.0".to_string(),
            config: test_config(),
            custom_start_command: None,
            init_password: None,
            jdk_install_path: None,
            mysql_install_path: None,
        };
        let err = p.start_command(&ctx).unwrap_err();
        assert!(err.to_string().contains("请先安装 JDK"));
    }
}
