use anyhow::Result;
use std::path::PathBuf;

use crate::models::software::{
    ArchiveFormat, ArchiveInfo, CatalogEntry, CatalogVersion, ConfigField, ConfigFieldType,
    ConfigSchema, HealthCheckSpec, LogSource, LogSourceKind, MirrorSource, SoftwareCategory,
};

use super::{
    ConfigContext, DataDirContext, HealthContext, InstallContext, LogContext, SoftwareProvider,
    StartCommand, StartContext, default_log_sources, resolve_data_dir,
};

#[cfg(windows)]
const CREATE_NO_WINDOW: u32 = 0x08000000;
#[cfg(not(windows))]
const CREATE_NO_WINDOW: u32 = 0;

fn config_str(c: &serde_json::Value, key: &str, default: &str) -> String {
    c.get(key)
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| default.to_string())
}

fn config_u64(c: &serde_json::Value, key: &str, default: u64) -> u64 {
    c.get(key).and_then(|v| v.as_u64()).unwrap_or(default)
}

pub struct KafkaProvider;

impl KafkaProvider {
    pub fn new() -> Self {
        Self
    }
}

impl Default for KafkaProvider {
    fn default() -> Self {
        Self::new()
    }
}

impl SoftwareProvider for KafkaProvider {
    fn key(&self) -> &str {
        "kafka"
    }

    fn catalog_entry(&self) -> CatalogEntry {
        // Kafka 官方包为 .tgz，跨平台（含 bin/kafka-server-start.sh 与 bin/windows/kafka-server-start.bat）。
        let version = "3.9.2".to_string();
        let url =
            "https://archive.apache.org/dist/kafka/3.9.2/kafka_2.13-3.9.2.tgz".to_string();
        let versions = vec![CatalogVersion {
            version: version.clone(),
            mirrors: vec![MirrorSource {
                name: "i18n:kafkaOfficial".to_string(),
                url,
                builtin: None,
            }],
            archive: ArchiveInfo {
                format: ArchiveFormat::TarGz,
                size: None,
                sha256: None,
            },
        }];

        CatalogEntry {
            key: "kafka".to_string(),
            name: "Kafka".to_string(),
            description: "分布式消息队列（Apache Kafka）".to_string(),
            description_i18n: Some("catalogDesc.kafka".to_string()),
            category: SoftwareCategory::MessageQueue,
            icon: "mdi:message-text-outline".to_string(),
            versions,
            default_version: version,
        }
    }

    fn post_install(&self, ctx: &InstallContext) -> Result<()> {
        // 预创建默认日志目录，并写入默认 server.properties（启动时会按 config 覆写）。
        let config_dir = ctx.install_dir().join("config");
        std::fs::create_dir_all(&config_dir)?;
        let log_dir = ctx.install_dir().join("data").join("kafka-logs");
        std::fs::create_dir_all(&log_dir)?;
        let props = format!(
            "# Generated by opx - Kafka (default)\n\
             broker.id=0\n\
             listeners=PLAINTEXT://:9092\n\
             log.dirs={log_dir}\n\
             num.partitions=1\n\
             default.replication.factor=1\n\
             offsets.topic.replication.factor=1\n\
             transaction.state.log.replication.factor=1\n\
             transaction.state.log.min.isr=1\n\
             auto.create.topics.enable=true\n\
             delete.topic.enable=true\n",
            log_dir = log_dir.to_string_lossy(),
        );
        std::fs::write(config_dir.join("server.properties"), props)?;
        Ok(())
    }

    fn start_command(&self, ctx: &StartContext) -> Result<StartCommand> {
        // Kafka 是 Java 应用：需要已安装 JDK，脚本前台启动。
        let jdk = ctx
            .jdk_install_path
            .as_deref()
            .ok_or_else(|| anyhow::anyhow!("请先安装 JDK/JRE 并在配置中选择后再启动"))?;

        let port = config_u64(&ctx.config, "port", 9092);
        let heap = config_str(&ctx.config, "heap", "1g");
        let log_dirs =
            resolve_data_dir(&ctx.config, "log_dirs", "data/kafka-logs", &ctx.install_path);

        // 按 config 生成 config/server.properties（覆盖 post_install 的默认值）。
        // .properties 不被 config_editor 支持，故由 Provider 自行生成（与 MinIO/RustFS 范式一致）。
        let config_dir = PathBuf::from(&ctx.install_path).join("config");
        std::fs::create_dir_all(&config_dir)?;
        let props = format!(
            "# Generated by opx - Kafka\n\
             broker.id=0\n\
             listeners=PLAINTEXT://:{port}\n\
             log.dirs={log_dirs}\n\
             num.partitions=1\n\
             default.replication.factor=1\n\
             offsets.topic.replication.factor=1\n\
             transaction.state.log.replication.factor=1\n\
             transaction.state.log.min.isr=1\n\
             auto.create.topics.enable=true\n\
             delete.topic.enable=true\n",
            port = port,
            log_dirs = log_dirs.to_string_lossy(),
        );
        std::fs::write(config_dir.join("server.properties"), props)?;

        let bin = if cfg!(windows) {
            "bin/windows/kafka-server-start.bat"
        } else {
            "bin/kafka-server-start.sh"
        };

        let mut env_vars = std::collections::BTreeMap::new();
        env_vars.insert("JAVA_HOME".to_string(), jdk.to_string());
        env_vars.insert(
            "KAFKA_HEAP_OPTS".to_string(),
            format!("-Xms{heap} -Xmx{heap}"),
        );

        Ok(StartCommand {
            program: bin.to_string(),
            args: vec!["config/server.properties".to_string()],
            env_vars,
            working_dir: PathBuf::from(&ctx.install_path),
            creation_flags: CREATE_NO_WINDOW,
            first_run_init: None,
        })
    }

    fn health_check(&self, ctx: &HealthContext) -> HealthCheckSpec {
        let port = ctx
            .config
            .get("port")
            .and_then(|v| v.as_u64())
            .map(|p| p as u16)
            .unwrap_or(if ctx.port > 0 { ctx.port } else { 9092 });
        HealthCheckSpec::Tcp {
            port,
            timeout_ms: 1000,
        }
    }

    fn config_schema(&self) -> Option<ConfigSchema> {
        Some(ConfigSchema {
            fields: vec![
                ConfigField {
                    key: "port".to_string(),
                    label_i18n: "configField.kafkaPort".to_string(),
                    field_type: ConfigFieldType::Port,
                    default_value: serde_json::json!(9092),
                    section: None,
                    description_i18n: Some("configField.kafkaPortDesc".to_string()),
                },
                ConfigField {
                    key: "heap".to_string(),
                    label_i18n: "configField.kafkaHeap".to_string(),
                    field_type: ConfigFieldType::Size {
                        units: vec!["m".to_string(), "g".to_string()],
                    },
                    default_value: serde_json::json!("1g"),
                    section: None,
                    description_i18n: Some("configField.kafkaHeapDesc".to_string()),
                },
                ConfigField {
                    key: "log_dirs".to_string(),
                    label_i18n: "configField.kafkaLogDirs".to_string(),
                    field_type: ConfigFieldType::Text,
                    default_value: serde_json::json!("data/kafka-logs"),
                    section: None,
                    description_i18n: Some("configField.kafkaLogDirsDesc".to_string()),
                },
                ConfigField {
                    key: "jdk".to_string(),
                    label_i18n: "configField.kafkaJdk".to_string(),
                    // options/labels 由 get_config_schema 命令层动态填充（已装 JDK/JRE）
                    field_type: ConfigFieldType::Select {
                        options: vec![],
                        labels: vec![],
                    },
                    default_value: serde_json::json!(""),
                    section: None,
                    description_i18n: Some("configField.kafkaJdkDesc".to_string()),
                },
            ],
            ephemeral_keys: vec![],
        })
    }

    fn log_sources(&self, ctx: &LogContext) -> Vec<LogSource> {
        let mut sources = default_log_sources(ctx);
        let file = PathBuf::from(&ctx.install_path)
            .join("logs")
            .join("server.log");
        sources.push(LogSource {
            path: file.to_string_lossy().to_string(),
            kind: LogSourceKind::ProviderFile,
            has_levels: true,
            level_pattern: None,
        });
        sources
    }

    fn data_dirs(&self, ctx: &DataDirContext) -> Vec<PathBuf> {
        vec![resolve_data_dir(
            &ctx.config,
            "log_dirs",
            "data/kafka-logs",
            &ctx.install_path,
        )]
    }

    fn min_jdk_version(&self) -> Option<u32> {
        // Kafka 3.x 需要 JDK 11+
        Some(11)
    }

    fn config_file_path(&self, _ctx: &ConfigContext) -> Option<PathBuf> {
        // .properties 不被 config_editor 支持，配置由 start_command 自行生成
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> serde_json::Value {
        serde_json::json!({
            "port": 9092,
            "heap": "1g",
            "log_dirs": "data/kafka-logs",
            "jdk": "",
        })
    }

    fn test_install_path() -> String {
        let p = std::env::temp_dir().join("opx_test_kafka");
        let _ = std::fs::create_dir_all(&p);
        p.to_string_lossy().to_string()
    }

    #[test]
    fn key_and_category() {
        let p = KafkaProvider::new();
        assert_eq!(p.key(), "kafka");
        assert_eq!(p.catalog_entry().category, SoftwareCategory::MessageQueue);
    }

    #[test]
    fn config_file_path_is_none() {
        let p = KafkaProvider::new();
        let ctx = ConfigContext {
            install_path: test_install_path(),
            version: "3.9.2".to_string(),
            config: test_config(),
        };
        assert!(p.config_file_path(&ctx).is_none());
    }

    #[test]
    fn min_jdk_version_is_11() {
        assert_eq!(KafkaProvider::new().min_jdk_version(), Some(11));
    }

    #[test]
    fn start_command_generates_server_properties() {
        let p = KafkaProvider::new();
        let install_path = test_install_path();
        let ctx = StartContext {
            installed_id: "kafka-1".to_string(),
            install_path: install_path.clone(),
            version: "3.9.2".to_string(),
            config: test_config(),
            custom_start_command: None,
            init_password: None,
            jdk_install_path: Some("C:\\jdk-17".to_string()),
            mysql_install_path: None,
        };
        let cmd = p.start_command(&ctx).expect("start_command ok");
        #[cfg(windows)]
        assert_eq!(cmd.program, "bin/windows/kafka-server-start.bat");
        #[cfg(not(windows))]
        assert_eq!(cmd.program, "bin/kafka-server-start.sh");
        assert_eq!(cmd.args, vec!["config/server.properties".to_string()]);
        assert_eq!(cmd.env_vars.get("JAVA_HOME"), Some(&"C:\\jdk-17".to_string()));
        assert!(cmd.env_vars.get("KAFKA_HEAP_OPTS").map(|s| s.contains("-Xmx1g")).unwrap_or(false));

        let props = std::fs::read_to_string(
            PathBuf::from(&install_path).join("config").join("server.properties"),
        )
        .expect("server.properties written");
        assert!(props.contains("listeners=PLAINTEXT://:9092"));
        assert!(props.contains("log.dirs="));
        assert!(props.contains("num.partitions=1"));
    }

    #[test]
    fn health_check_is_tcp_9092() {
        let p = KafkaProvider::new();
        let hc = p.health_check(&HealthContext {
            installed_id: "kafka-1".to_string(),
            install_path: test_install_path(),
            port: 0,
            config: test_config(),
        });
        match hc {
            HealthCheckSpec::Tcp { port, timeout_ms } => {
                assert_eq!(port, 9092);
                assert_eq!(timeout_ms, 1000);
            }
            _ => panic!("expected Tcp health check"),
        }
    }

    #[test]
    fn start_command_errors_without_jdk() {
        let p = KafkaProvider::new();
        let ctx = StartContext {
            installed_id: "kafka-1".to_string(),
            install_path: test_install_path(),
            version: "3.9.2".to_string(),
            config: test_config(),
            custom_start_command: None,
            init_password: None,
            jdk_install_path: None,
            mysql_install_path: None,
        };
        let err = p.start_command(&ctx).unwrap_err();
        assert!(err.to_string().contains("请先安装 JDK"));
    }
}
